# Generated by Django 4.1 on 2022-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToRepairs',
            fields=[
                ('rep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_mtr', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'to_repairs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToShedule',
            fields=[
                ('shed_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'to_shedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToServices',
            fields=[
                ('ser_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_to', models.IntegerField()),
                ('type_work', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'to_service',
                'managed': True,
            },
        ),
    ]
