# Generated by Django 4.1 on 2022-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sys', models.SmallIntegerField()),
                ('uid_eq', models.UUIDField()),
                ('desc_eq', models.CharField(max_length=255)),
                ('count_eq', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_bur', models.UUIDField()),
                ('desc_bur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_sys', models.UUIDField()),
                ('desc_sys', models.CharField(max_length=255)),
                ('id_obj', models.IntegerField()),
            ],
        ),
    ]
