# Generated by Django 4.1 on 2022-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projbur_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefEquip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_sys', models.SmallIntegerField()),
                ('uid_eq', models.UUIDField()),
                ('desc_eq', models.CharField(max_length=255)),
                ('count_eq', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'guide.ref_equip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefObj',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid_bur', models.UUIDField()),
                ('desc_bur', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'guide.ref_obj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefSys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid_sys', models.UUIDField()),
                ('desc_sys', models.CharField(max_length=255)),
                ('id_obj', models.IntegerField()),
            ],
            options={
                'db_table': 'guide.ref_sys',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ref_Equip',
        ),
        migrations.DeleteModel(
            name='Ref_Obj',
        ),
        migrations.DeleteModel(
            name='Ref_Sys',
        ),
    ]
