# Generated by Django 4.1 on 2022-08-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projbur_app', '0002_refequip_refobj_refsys_delete_ref_equip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refequip',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='refobj',
            table='ref_obj',
        ),
        migrations.AlterModelTable(
            name='refsys',
            table='ref_sys',
        ),
    ]
